// <auto-generated />
using Acai.Api.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Acai.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Acai.Api.Domain.Models.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("TempoMinutos");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Adicional");
                });

            modelBuilder.Entity("Acai.Api.Domain.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("SaborId");

                    b.Property<int>("TamanhoId");

                    b.Property<decimal>("ValorTotalPedido");

                    b.HasKey("Id");

                    b.HasIndex("SaborId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Acai.Api.Domain.Models.PedidoAdicional", b =>
                {
                    b.Property<int>("AdicionalId");

                    b.Property<int>("PedidoId");

                    b.HasKey("AdicionalId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pedido_Adicional");
                });

            modelBuilder.Entity("Acai.Api.Domain.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("TempoMinutos");

                    b.HasKey("Id");

                    b.ToTable("Sabor");
                });

            modelBuilder.Entity("Acai.Api.Domain.Models.Tamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Ml")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<int>("TempoMinutos");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Tamanho");
                });

            modelBuilder.Entity("Acai.Api.Domain.Models.Pedido", b =>
                {
                    b.HasOne("Acai.Api.Domain.Models.Sabor", "Sabor")
                        .WithMany("Pedidos")
                        .HasForeignKey("SaborId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Acai.Api.Domain.Models.Tamanho", "Tamanho")
                        .WithMany("Pedidos")
                        .HasForeignKey("TamanhoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Acai.Api.Domain.Models.PedidoAdicional", b =>
                {
                    b.HasOne("Acai.Api.Domain.Models.Adicional", "Adicional")
                        .WithMany("pedidoAdicionals")
                        .HasForeignKey("AdicionalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Acai.Api.Domain.Models.Pedido", "Pedido")
                        .WithMany("pedidoAdicionals")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
